version: '3.8'

services:
  app:
    build: .
    container_name: streamlit_con
    ports:
      - "8501:8501"
    depends_on:
      - app-db
    environment:
      POSTGRES_HOST: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432

  app-db:
    image: postgres:15
    container_name: postgres_con
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
